#!/bin/bash
PDFLATEX=$(which pdflatex)
SELF_BASE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BUILD_PATH="$SELF_BASE/output"
PDFLATEX_OPTS="-output-directory $BUILD_PATH"
TEXFILE="$SELF_BASE/CV/Curriculum.tex"
INCLUDES_PATH="$SELF_BASE/Includes/CV"
TEX_INCLUDES_PATH="$SELF_BASE/tex"
GIT=$(which git)
GONAL_REPO="git@github.com:GonzaloAlvarez/gonal.git"
export TEXMFHOME="$SELF_BASE"

if [ ! -e "$BUILD_PATH" ]; then
	mkdir -p "$BUILD_PATH"
fi

rm -Rf "$TEX_INCLUDES_PATH"
mkdir -p "$TEX_INCLUDES_PATH"
ln -s "$INCLUDES_PATH" "$TEX_INCLUDES_PATH/latex"

if [ -z "$PDFLATEX" ]; then
	echo "ERROR: pdflatex does not exist"
	exit 1
fi

$PDFLATEX $PDFLATEX_OPTS $TEXFILE

rm -Rf "$TEX_INCLUDES_PATH"
exit 0
$GIT clone $GONAL_REPO $BUILD_PATH/gonal
cp $BUILD_PATH/Curriculum.pdf $BUILD_PATH/gonal/static/cv/CV-GonzaloAlvarez.pdf
cd $BUILD_PATH/gonal
git commit -a -m "Updated copy of the CV"
git push
